// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgRemoveKyc } from "./types/rollapp/kyc/tx";
import { MsgUpdateCredential } from "./types/rollapp/kyc/tx";
import { MsgUpdateDID } from "./types/rollapp/kyc/tx";
import { MsgUpdateKycInfo } from "./types/rollapp/kyc/tx";

import { Credential as typeCredential} from "./types"
import { Did as typeDid} from "./types"
import { DidInfo as typeDidInfo} from "./types"
import { KYCCredential as typeKYCCredential} from "./types"
import { KycEventSeq as typeKycEventSeq} from "./types"
import { KycPacketData as typeKycPacketData} from "./types"
import { NoData as typeNoData} from "./types"
import { IbcKycPacketData as typeIbcKycPacketData} from "./types"
import { IbcKycPacketAck as typeIbcKycPacketAck} from "./types"
import { Params as typeParams} from "./types"
import { QueryMeKycsRequest as typeQueryMeKycsRequest} from "./types"
import { QueryMeKycsResponse as typeQueryMeKycsResponse} from "./types"
import { QueryMeDidInfoRequest as typeQueryMeDidInfoRequest} from "./types"
import { QueryMeDidInfoResponse as typeQueryMeDidInfoResponse} from "./types"
import { item as typeitem} from "./types"

export { MsgRemoveKyc, MsgUpdateCredential, MsgUpdateDID, MsgUpdateKycInfo };

type sendMsgRemoveKycParams = {
  value: MsgRemoveKyc,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateCredentialParams = {
  value: MsgUpdateCredential,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDIDParams = {
  value: MsgUpdateDID,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateKycInfoParams = {
  value: MsgUpdateKycInfo,
  fee?: StdFee,
  memo?: string
};


type msgRemoveKycParams = {
  value: MsgRemoveKyc,
};

type msgUpdateCredentialParams = {
  value: MsgUpdateCredential,
};

type msgUpdateDIDParams = {
  value: MsgUpdateDID,
};

type msgUpdateKycInfoParams = {
  value: MsgUpdateKycInfo,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgRemoveKyc({ value, fee, memo }: sendMsgRemoveKycParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveKyc: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRemoveKyc({ value: MsgRemoveKyc.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveKyc: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateCredential({ value, fee, memo }: sendMsgUpdateCredentialParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateCredential: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateCredential({ value: MsgUpdateCredential.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateCredential: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateDID({ value, fee, memo }: sendMsgUpdateDIDParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDID: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateDID({ value: MsgUpdateDID.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDID: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateKycInfo({ value, fee, memo }: sendMsgUpdateKycInfoParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateKycInfo: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateKycInfo({ value: MsgUpdateKycInfo.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateKycInfo: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgRemoveKyc({ value }: msgRemoveKycParams): EncodeObject {
			try {
				return { typeUrl: "/stchain.rollapp.kyc.MsgRemoveKyc", value: MsgRemoveKyc.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveKyc: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateCredential({ value }: msgUpdateCredentialParams): EncodeObject {
			try {
				return { typeUrl: "/stchain.rollapp.kyc.MsgUpdateCredential", value: MsgUpdateCredential.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateCredential: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateDID({ value }: msgUpdateDIDParams): EncodeObject {
			try {
				return { typeUrl: "/stchain.rollapp.kyc.MsgUpdateDID", value: MsgUpdateDID.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDID: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateKycInfo({ value }: msgUpdateKycInfoParams): EncodeObject {
			try {
				return { typeUrl: "/stchain.rollapp.kyc.MsgUpdateKycInfo", value: MsgUpdateKycInfo.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateKycInfo: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Credential: getStructure(typeCredential.fromPartial({})),
						Did: getStructure(typeDid.fromPartial({})),
						DidInfo: getStructure(typeDidInfo.fromPartial({})),
						KYCCredential: getStructure(typeKYCCredential.fromPartial({})),
						KycEventSeq: getStructure(typeKycEventSeq.fromPartial({})),
						KycPacketData: getStructure(typeKycPacketData.fromPartial({})),
						NoData: getStructure(typeNoData.fromPartial({})),
						IbcKycPacketData: getStructure(typeIbcKycPacketData.fromPartial({})),
						IbcKycPacketAck: getStructure(typeIbcKycPacketAck.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						QueryMeKycsRequest: getStructure(typeQueryMeKycsRequest.fromPartial({})),
						QueryMeKycsResponse: getStructure(typeQueryMeKycsResponse.fromPartial({})),
						QueryMeDidInfoRequest: getStructure(typeQueryMeDidInfoRequest.fromPartial({})),
						QueryMeDidInfoResponse: getStructure(typeQueryMeDidInfoResponse.fromPartial({})),
						item: getStructure(typeitem.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			StchainRollappKyc: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;