// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollapp/kyc/did_info.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// kyc level enum
type KycLevel int32

const (
	KYC_LEVEL_NONE KycLevel = 0
	KYC_LEVEL_ONE  KycLevel = 1
	KYC_LEVEL_TWO  KycLevel = 2
)

var KycLevel_name = map[int32]string{
	0: "KYC_LEVEL_NONE",
	1: "KYC_LEVEL_ONE",
	2: "KYC_LEVEL_TWO",
}

var KycLevel_value = map[string]int32{
	"KYC_LEVEL_NONE": 0,
	"KYC_LEVEL_ONE":  1,
	"KYC_LEVEL_TWO":  2,
}

func (x KycLevel) String() string {
	return proto.EnumName(KycLevel_name, int32(x))
}

func (KycLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_70fa212fb88566a6, []int{0}
}

// did status enum
type DidStatus int32

const (
	DID_STATUS_DEACTIVE DidStatus = 0
	DID_STATUS_ACTIVE   DidStatus = 1
)

var DidStatus_name = map[int32]string{
	0: "DID_STATUS_DEACTIVE",
	1: "DID_STATUS_ACTIVE",
}

var DidStatus_value = map[string]int32{
	"DID_STATUS_DEACTIVE": 0,
	"DID_STATUS_ACTIVE":   1,
}

func (x DidStatus) String() string {
	return proto.EnumName(DidStatus_name, int32(x))
}

func (DidStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_70fa212fb88566a6, []int{1}
}

type DidInfo struct {
	Did     string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// public_key is mapped to the user address
	// the issuer will use public_key to encrypt the user's certificate to ensure the privacy of the off-chain certificate
	Pubkey   string    `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Status   DidStatus `protobuf:"varint,4,opt,name=status,proto3,enum=stchain.rollapp.kyc.DidStatus" json:"status,omitempty"`
	RegionId string    `protobuf:"bytes,5,opt,name=regionId,proto3" json:"regionId,omitempty"`
	KycLevel KycLevel  `protobuf:"varint,6,opt,name=kycLevel,proto3,enum=stchain.rollapp.kyc.KycLevel" json:"kycLevel,omitempty"`
}

func (m *DidInfo) Reset()         { *m = DidInfo{} }
func (m *DidInfo) String() string { return proto.CompactTextString(m) }
func (*DidInfo) ProtoMessage()    {}
func (*DidInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_70fa212fb88566a6, []int{0}
}
func (m *DidInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DidInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DidInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DidInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DidInfo.Merge(m, src)
}
func (m *DidInfo) XXX_Size() int {
	return m.Size()
}
func (m *DidInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DidInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DidInfo proto.InternalMessageInfo

func (m *DidInfo) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *DidInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DidInfo) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *DidInfo) GetStatus() DidStatus {
	if m != nil {
		return m.Status
	}
	return DID_STATUS_DEACTIVE
}

func (m *DidInfo) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *DidInfo) GetKycLevel() KycLevel {
	if m != nil {
		return m.KycLevel
	}
	return KYC_LEVEL_NONE
}

func init() {
	proto.RegisterEnum("stchain.rollapp.kyc.KycLevel", KycLevel_name, KycLevel_value)
	proto.RegisterEnum("stchain.rollapp.kyc.DidStatus", DidStatus_name, DidStatus_value)
	proto.RegisterType((*DidInfo)(nil), "stchain.rollapp.kyc.DidInfo")
}

func init() { proto.RegisterFile("rollapp/kyc/did_info.proto", fileDescriptor_70fa212fb88566a6) }

var fileDescriptor_70fa212fb88566a6 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0xe3, 0x0d, 0xba, 0xce, 0x12, 0xa5, 0x73, 0x0b, 0x0a, 0x96, 0xb0, 0x2c, 0x04, 0xda,
	0x34, 0xb1, 0x44, 0x0c, 0x09, 0x89, 0x63, 0xb7, 0xf4, 0x50, 0xad, 0xda, 0xa4, 0xb6, 0x0c, 0xc1,
	0x25, 0x6a, 0xe3, 0x2c, 0xb3, 0xda, 0xc5, 0x51, 0xec, 0x4e, 0xe4, 0x0d, 0x50, 0x4e, 0xbc, 0x40,
	0x4e, 0x70, 0xe0, 0x01, 0x78, 0x08, 0x8e, 0x13, 0x27, 0x8e, 0xa8, 0x7d, 0x07, 0xce, 0x28, 0x4e,
	0xda, 0xad, 0xa2, 0xb7, 0xef, 0xfb, 0xff, 0x7f, 0xfe, 0xdb, 0x9f, 0xf5, 0x41, 0x1c, 0x8b, 0xc9,
	0x64, 0x18, 0x45, 0xf6, 0x38, 0xf1, 0x6c, 0xc6, 0x99, 0xcb, 0xc3, 0x0b, 0x61, 0x45, 0xb1, 0x50,
	0x02, 0x35, 0xa4, 0xf2, 0x2e, 0x87, 0x3c, 0xb4, 0x4a, 0xc6, 0x1a, 0x27, 0x1e, 0x6e, 0x06, 0x22,
	0x10, 0xda, 0xb7, 0xf3, 0xaa, 0x40, 0xf1, 0x13, 0x4f, 0xc8, 0x2b, 0x21, 0xdd, 0xc2, 0x28, 0x9a,
	0xc2, 0x7a, 0xf6, 0x17, 0xc0, 0x2d, 0x87, 0xb3, 0x4e, 0x78, 0x21, 0x50, 0x1d, 0x6e, 0x32, 0xce,
	0x4c, 0x40, 0xc1, 0xde, 0x76, 0x2f, 0x2f, 0xd1, 0x21, 0xdc, 0x1a, 0x32, 0x16, 0xfb, 0x52, 0x9a,
	0x1b, 0xb9, 0x7a, 0x64, 0xfe, 0xfa, 0x71, 0xd0, 0x2c, 0x03, 0x5a, 0x85, 0xd3, 0x57, 0x31, 0x0f,
	0x83, 0xde, 0x02, 0x44, 0x8f, 0x61, 0x25, 0x9a, 0x8e, 0xc6, 0x7e, 0x62, 0x6e, 0xea, 0xa0, 0xb2,
	0x43, 0x6f, 0x60, 0x45, 0xaa, 0xa1, 0x9a, 0x4a, 0xf3, 0x1e, 0x05, 0x7b, 0xb5, 0x43, 0x62, 0xad,
	0x19, 0xc0, 0x72, 0x38, 0xeb, 0x6b, 0xaa, 0x57, 0xd2, 0x08, 0xc3, 0x6a, 0xec, 0x07, 0x5c, 0x84,
	0x1d, 0x66, 0xde, 0xd7, 0x89, 0xcb, 0x1e, 0xbd, 0x85, 0xd5, 0x71, 0xe2, 0x75, 0xfd, 0x6b, 0x7f,
	0x62, 0x56, 0x74, 0xea, 0xd3, 0xb5, 0xa9, 0x27, 0x25, 0xd4, 0x5b, 0xe2, 0xfb, 0x29, 0x80, 0xd5,
	0x85, 0x8c, 0x76, 0x61, 0xed, 0xe4, 0xc3, 0xb1, 0xdb, 0x6d, 0x9f, 0xb7, 0xbb, 0xee, 0xe9, 0xd9,
	0x69, 0xbb, 0x6e, 0xe0, 0x46, 0x9a, 0xd1, 0x87, 0xab, 0x2a, 0x45, 0x2f, 0xe0, 0x83, 0x5b, 0x29,
	0xe7, 0x00, 0x46, 0x69, 0x46, 0x6b, 0x2b, 0x22, 0x45, 0xcf, 0xef, 0x62, 0x83, 0xf7, 0x67, 0xf5,
	0x0d, 0xbc, 0x93, 0x66, 0x74, 0x55, 0xc4, 0xd5, 0xcf, 0x5f, 0x89, 0xf1, 0xfd, 0x1b, 0x01, 0xfb,
	0xd7, 0x70, 0x7b, 0x39, 0x38, 0x7a, 0x05, 0x1b, 0x4e, 0xc7, 0x71, 0xfb, 0x83, 0xd6, 0xe0, 0x5d,
	0xdf, 0x75, 0xda, 0xad, 0xe3, 0x41, 0xe7, 0x3c, 0x7f, 0x91, 0x99, 0x66, 0xb4, 0xb9, 0xc6, 0xa2,
	0xe8, 0x25, 0xdc, 0xb9, 0xa3, 0x97, 0x07, 0x00, 0x7e, 0x94, 0x66, 0xf4, 0x7f, 0xe3, 0xf6, 0xde,
	0xa3, 0xd6, 0xcf, 0x19, 0x01, 0x37, 0x33, 0x02, 0xfe, 0xcc, 0x08, 0xf8, 0x32, 0x27, 0xc6, 0xcd,
	0x9c, 0x18, 0xbf, 0xe7, 0xc4, 0xf8, 0xb8, 0x1b, 0x70, 0x75, 0x39, 0x1d, 0x59, 0x9e, 0xb8, 0xb2,
	0xa5, 0x3a, 0xd0, 0x5f, 0x6a, 0x2f, 0xb6, 0xf1, 0x93, 0xde, 0x47, 0x95, 0x44, 0xbe, 0x1c, 0x55,
	0xf4, 0x1e, 0xbd, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x9b, 0x32, 0x5b, 0xab, 0x02, 0x00,
	0x00,
}

func (m *DidInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DidInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DidInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.KycLevel != 0 {
		i = encodeVarintDidInfo(dAtA, i, uint64(m.KycLevel))
		i--
		dAtA[i] = 0x30
	}
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintDidInfo(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Status != 0 {
		i = encodeVarintDidInfo(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Pubkey) > 0 {
		i -= len(m.Pubkey)
		copy(dAtA[i:], m.Pubkey)
		i = encodeVarintDidInfo(dAtA, i, uint64(len(m.Pubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintDidInfo(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintDidInfo(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDidInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovDidInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DidInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovDidInfo(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovDidInfo(uint64(l))
	}
	l = len(m.Pubkey)
	if l > 0 {
		n += 1 + l + sovDidInfo(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovDidInfo(uint64(m.Status))
	}
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovDidInfo(uint64(l))
	}
	if m.KycLevel != 0 {
		n += 1 + sovDidInfo(uint64(m.KycLevel))
	}
	return n
}

func sovDidInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDidInfo(x uint64) (n int) {
	return sovDidInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DidInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDidInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DidInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DidInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDidInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDidInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDidInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDidInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDidInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDidInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= DidStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDidInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDidInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KycLevel", wireType)
			}
			m.KycLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KycLevel |= KycLevel(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDidInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDidInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDidInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDidInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDidInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDidInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDidInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDidInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDidInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDidInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDidInfo = fmt.Errorf("proto: unexpected end of group")
)
