// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollapp/kyc/kyc_info.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type KycInfo struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	IsMeid  bool   `protobuf:"varint,2,opt,name=isMeid,proto3" json:"isMeid,omitempty"`
}

func (m *KycInfo) Reset()         { *m = KycInfo{} }
func (m *KycInfo) String() string { return proto.CompactTextString(m) }
func (*KycInfo) ProtoMessage()    {}
func (*KycInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9f54a7e1781d7e5, []int{0}
}
func (m *KycInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KycInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KycInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KycInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KycInfo.Merge(m, src)
}
func (m *KycInfo) XXX_Size() int {
	return m.Size()
}
func (m *KycInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KycInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KycInfo proto.InternalMessageInfo

func (m *KycInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *KycInfo) GetIsMeid() bool {
	if m != nil {
		return m.IsMeid
	}
	return false
}

func init() {
	proto.RegisterType((*KycInfo)(nil), "stchain.rollapp.kyc.KycInfo")
}

func init() { proto.RegisterFile("rollapp/kyc/kyc_info.proto", fileDescriptor_a9f54a7e1781d7e5) }

var fileDescriptor_a9f54a7e1781d7e5 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0xca, 0xcf, 0xc9,
	0x49, 0x2c, 0x28, 0xd0, 0xcf, 0xae, 0x4c, 0x06, 0xe1, 0xf8, 0xcc, 0xbc, 0xb4, 0x7c, 0xbd, 0x82,
	0xa2, 0xfc, 0x92, 0x7c, 0x21, 0xe1, 0xe2, 0x92, 0xe4, 0x8c, 0xc4, 0xcc, 0x3c, 0x3d, 0xa8, 0x1a,
	0xbd, 0xec, 0xca, 0x64, 0x25, 0x6b, 0x2e, 0x76, 0xef, 0xca, 0x64, 0xcf, 0xbc, 0xb4, 0x7c, 0x21,
	0x09, 0x2e, 0xf6, 0xc4, 0x94, 0x94, 0xa2, 0xd4, 0xe2, 0x62, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x18, 0x57, 0x48, 0x8c, 0x8b, 0x2d, 0xb3, 0xd8, 0x37, 0x35, 0x33, 0x45, 0x82, 0x49, 0x81,
	0x51, 0x83, 0x23, 0x08, 0xca, 0x73, 0x72, 0x3c, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6,
	0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39,
	0x86, 0x28, 0xf5, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xe2, 0x12,
	0x5d, 0xb0, 0xbd, 0xfa, 0x30, 0xb7, 0x55, 0x80, 0x5d, 0x57, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4,
	0x06, 0x76, 0x9b, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xfe, 0x5c, 0xda, 0xb9, 0x00, 0x00,
	0x00,
}

func (m *KycInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KycInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KycInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsMeid {
		i--
		if m.IsMeid {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintKycInfo(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintKycInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovKycInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KycInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovKycInfo(uint64(l))
	}
	if m.IsMeid {
		n += 2
	}
	return n
}

func sovKycInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozKycInfo(x uint64) (n int) {
	return sovKycInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KycInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKycInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KycInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KycInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKycInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKycInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKycInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsMeid", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKycInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsMeid = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipKycInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKycInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipKycInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowKycInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKycInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKycInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthKycInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupKycInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthKycInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthKycInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowKycInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupKycInfo = fmt.Errorf("proto: unexpected end of group")
)
