// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollapp/kyc/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateDID struct {
	Creator     string  `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ProofHeight uint64  `protobuf:"varint,2,opt,name=proofHeight,proto3" json:"proofHeight,omitempty"`
	StoreHash   []byte  `protobuf:"bytes,3,opt,name=storeHash,proto3" json:"storeHash,omitempty"`
	StoreProof  []byte  `protobuf:"bytes,4,opt,name=storeProof,proto3" json:"storeProof,omitempty"`
	Proofs      []byte  `protobuf:"bytes,5,opt,name=proofs,proto3" json:"proofs,omitempty"`
	Dids        []*Item `protobuf:"bytes,6,rep,name=dids,proto3" json:"dids,omitempty"`
}

func (m *MsgUpdateDID) Reset()         { *m = MsgUpdateDID{} }
func (m *MsgUpdateDID) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateDID) ProtoMessage()    {}
func (*MsgUpdateDID) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d910db27c137d0, []int{0}
}
func (m *MsgUpdateDID) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateDID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateDID.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateDID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateDID.Merge(m, src)
}
func (m *MsgUpdateDID) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateDID) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateDID.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateDID proto.InternalMessageInfo

func (m *MsgUpdateDID) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateDID) GetProofHeight() uint64 {
	if m != nil {
		return m.ProofHeight
	}
	return 0
}

func (m *MsgUpdateDID) GetStoreHash() []byte {
	if m != nil {
		return m.StoreHash
	}
	return nil
}

func (m *MsgUpdateDID) GetStoreProof() []byte {
	if m != nil {
		return m.StoreProof
	}
	return nil
}

func (m *MsgUpdateDID) GetProofs() []byte {
	if m != nil {
		return m.Proofs
	}
	return nil
}

func (m *MsgUpdateDID) GetDids() []*Item {
	if m != nil {
		return m.Dids
	}
	return nil
}

type MsgUpdateDIDResponse struct {
}

func (m *MsgUpdateDIDResponse) Reset()         { *m = MsgUpdateDIDResponse{} }
func (m *MsgUpdateDIDResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateDIDResponse) ProtoMessage()    {}
func (*MsgUpdateDIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d910db27c137d0, []int{1}
}
func (m *MsgUpdateDIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateDIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateDIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateDIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateDIDResponse.Merge(m, src)
}
func (m *MsgUpdateDIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateDIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateDIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateDIDResponse proto.InternalMessageInfo

type MsgUpdateCredential struct {
	Creator     string  `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ProofHeight uint64  `protobuf:"varint,2,opt,name=proofHeight,proto3" json:"proofHeight,omitempty"`
	StoreHash   []byte  `protobuf:"bytes,3,opt,name=storeHash,proto3" json:"storeHash,omitempty"`
	StoreProof  []byte  `protobuf:"bytes,4,opt,name=storeProof,proto3" json:"storeProof,omitempty"`
	Proofs      []byte  `protobuf:"bytes,5,opt,name=proofs,proto3" json:"proofs,omitempty"`
	Credentials []*Item `protobuf:"bytes,6,rep,name=credentials,proto3" json:"credentials,omitempty"`
}

func (m *MsgUpdateCredential) Reset()         { *m = MsgUpdateCredential{} }
func (m *MsgUpdateCredential) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCredential) ProtoMessage()    {}
func (*MsgUpdateCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d910db27c137d0, []int{2}
}
func (m *MsgUpdateCredential) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCredential.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCredential.Merge(m, src)
}
func (m *MsgUpdateCredential) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCredential.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCredential proto.InternalMessageInfo

func (m *MsgUpdateCredential) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateCredential) GetProofHeight() uint64 {
	if m != nil {
		return m.ProofHeight
	}
	return 0
}

func (m *MsgUpdateCredential) GetStoreHash() []byte {
	if m != nil {
		return m.StoreHash
	}
	return nil
}

func (m *MsgUpdateCredential) GetStoreProof() []byte {
	if m != nil {
		return m.StoreProof
	}
	return nil
}

func (m *MsgUpdateCredential) GetProofs() []byte {
	if m != nil {
		return m.Proofs
	}
	return nil
}

func (m *MsgUpdateCredential) GetCredentials() []*Item {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type MsgUpdateCredentialResponse struct {
}

func (m *MsgUpdateCredentialResponse) Reset()         { *m = MsgUpdateCredentialResponse{} }
func (m *MsgUpdateCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCredentialResponse) ProtoMessage()    {}
func (*MsgUpdateCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d910db27c137d0, []int{3}
}
func (m *MsgUpdateCredentialResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCredentialResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCredentialResponse.Merge(m, src)
}
func (m *MsgUpdateCredentialResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCredentialResponse proto.InternalMessageInfo

type Item struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d910db27c137d0, []int{4}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Item.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return m.Size()
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Item) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type MsgRemoveKyc struct {
	Creator     string  `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ProofHeight uint64  `protobuf:"varint,2,opt,name=proofHeight,proto3" json:"proofHeight,omitempty"`
	StoreHash   []byte  `protobuf:"bytes,3,opt,name=storeHash,proto3" json:"storeHash,omitempty"`
	StoreProof  []byte  `protobuf:"bytes,4,opt,name=storeProof,proto3" json:"storeProof,omitempty"`
	Proofs      []byte  `protobuf:"bytes,5,opt,name=proofs,proto3" json:"proofs,omitempty"`
	Credentials []*Item `protobuf:"bytes,6,rep,name=credentials,proto3" json:"credentials,omitempty"`
}

func (m *MsgRemoveKyc) Reset()         { *m = MsgRemoveKyc{} }
func (m *MsgRemoveKyc) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveKyc) ProtoMessage()    {}
func (*MsgRemoveKyc) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d910db27c137d0, []int{5}
}
func (m *MsgRemoveKyc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveKyc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveKyc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveKyc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveKyc.Merge(m, src)
}
func (m *MsgRemoveKyc) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveKyc) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveKyc.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveKyc proto.InternalMessageInfo

func (m *MsgRemoveKyc) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRemoveKyc) GetProofHeight() uint64 {
	if m != nil {
		return m.ProofHeight
	}
	return 0
}

func (m *MsgRemoveKyc) GetStoreHash() []byte {
	if m != nil {
		return m.StoreHash
	}
	return nil
}

func (m *MsgRemoveKyc) GetStoreProof() []byte {
	if m != nil {
		return m.StoreProof
	}
	return nil
}

func (m *MsgRemoveKyc) GetProofs() []byte {
	if m != nil {
		return m.Proofs
	}
	return nil
}

func (m *MsgRemoveKyc) GetCredentials() []*Item {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type MsgRemoveKycResponse struct {
}

func (m *MsgRemoveKycResponse) Reset()         { *m = MsgRemoveKycResponse{} }
func (m *MsgRemoveKycResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveKycResponse) ProtoMessage()    {}
func (*MsgRemoveKycResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d910db27c137d0, []int{6}
}
func (m *MsgRemoveKycResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveKycResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveKycResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveKycResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveKycResponse.Merge(m, src)
}
func (m *MsgRemoveKycResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveKycResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveKycResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveKycResponse proto.InternalMessageInfo

type MsgUpdateKycInfo struct {
	Creator     string  `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ProofHeight uint64  `protobuf:"varint,2,opt,name=proofHeight,proto3" json:"proofHeight,omitempty"`
	StoreHash   []byte  `protobuf:"bytes,3,opt,name=storeHash,proto3" json:"storeHash,omitempty"`
	StoreProof  []byte  `protobuf:"bytes,4,opt,name=storeProof,proto3" json:"storeProof,omitempty"`
	Proofs      []byte  `protobuf:"bytes,5,opt,name=proofs,proto3" json:"proofs,omitempty"`
	DidInfos    []*Item `protobuf:"bytes,6,rep,name=didInfos,proto3" json:"didInfos,omitempty"`
}

func (m *MsgUpdateKycInfo) Reset()         { *m = MsgUpdateKycInfo{} }
func (m *MsgUpdateKycInfo) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateKycInfo) ProtoMessage()    {}
func (*MsgUpdateKycInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d910db27c137d0, []int{7}
}
func (m *MsgUpdateKycInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateKycInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateKycInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateKycInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateKycInfo.Merge(m, src)
}
func (m *MsgUpdateKycInfo) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateKycInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateKycInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateKycInfo proto.InternalMessageInfo

func (m *MsgUpdateKycInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateKycInfo) GetProofHeight() uint64 {
	if m != nil {
		return m.ProofHeight
	}
	return 0
}

func (m *MsgUpdateKycInfo) GetStoreHash() []byte {
	if m != nil {
		return m.StoreHash
	}
	return nil
}

func (m *MsgUpdateKycInfo) GetStoreProof() []byte {
	if m != nil {
		return m.StoreProof
	}
	return nil
}

func (m *MsgUpdateKycInfo) GetProofs() []byte {
	if m != nil {
		return m.Proofs
	}
	return nil
}

func (m *MsgUpdateKycInfo) GetDidInfos() []*Item {
	if m != nil {
		return m.DidInfos
	}
	return nil
}

type MsgUpdateKycInfoResponse struct {
}

func (m *MsgUpdateKycInfoResponse) Reset()         { *m = MsgUpdateKycInfoResponse{} }
func (m *MsgUpdateKycInfoResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateKycInfoResponse) ProtoMessage()    {}
func (*MsgUpdateKycInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02d910db27c137d0, []int{8}
}
func (m *MsgUpdateKycInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateKycInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateKycInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateKycInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateKycInfoResponse.Merge(m, src)
}
func (m *MsgUpdateKycInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateKycInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateKycInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateKycInfoResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateDID)(nil), "stchain.rollapp.kyc.MsgUpdateDID")
	proto.RegisterType((*MsgUpdateDIDResponse)(nil), "stchain.rollapp.kyc.MsgUpdateDIDResponse")
	proto.RegisterType((*MsgUpdateCredential)(nil), "stchain.rollapp.kyc.MsgUpdateCredential")
	proto.RegisterType((*MsgUpdateCredentialResponse)(nil), "stchain.rollapp.kyc.MsgUpdateCredentialResponse")
	proto.RegisterType((*Item)(nil), "stchain.rollapp.kyc.item")
	proto.RegisterType((*MsgRemoveKyc)(nil), "stchain.rollapp.kyc.MsgRemoveKyc")
	proto.RegisterType((*MsgRemoveKycResponse)(nil), "stchain.rollapp.kyc.MsgRemoveKycResponse")
	proto.RegisterType((*MsgUpdateKycInfo)(nil), "stchain.rollapp.kyc.MsgUpdateKycInfo")
	proto.RegisterType((*MsgUpdateKycInfoResponse)(nil), "stchain.rollapp.kyc.MsgUpdateKycInfoResponse")
}

func init() { proto.RegisterFile("rollapp/kyc/tx.proto", fileDescriptor_02d910db27c137d0) }

var fileDescriptor_02d910db27c137d0 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x95, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x6b, 0xd2, 0x15, 0xfa, 0x5a, 0xa4, 0xca, 0xab, 0x26, 0x53, 0x20, 0x0a, 0x91, 0x10,
	0xe1, 0xd0, 0x14, 0x0d, 0x71, 0xe2, 0x04, 0xec, 0xb0, 0x69, 0x9a, 0x84, 0x2c, 0x71, 0x18, 0xb7,
	0xcc, 0xf1, 0xda, 0xa8, 0x6d, 0x1c, 0xc5, 0xde, 0xb4, 0xfc, 0x17, 0x88, 0xbf, 0x8a, 0x1b, 0x3b,
	0x22, 0x21, 0x24, 0xd4, 0xf2, 0x87, 0xa0, 0x3a, 0x8d, 0x13, 0x58, 0x37, 0x72, 0x9c, 0xb8, 0xe5,
	0xf9, 0x7d, 0xdf, 0x8f, 0xcf, 0xd3, 0x8b, 0x0d, 0xfd, 0x54, 0xcc, 0x66, 0x41, 0x92, 0x8c, 0xa6,
	0x19, 0x1b, 0xa9, 0x0b, 0x3f, 0x49, 0x85, 0x12, 0x78, 0x5b, 0x2a, 0x36, 0x09, 0xa2, 0xd8, 0x5f,
	0x7b, 0xfd, 0x69, 0xc6, 0xdc, 0xaf, 0x08, 0xba, 0x47, 0x72, 0xfc, 0x21, 0x09, 0x03, 0xc5, 0xf7,
	0x0e, 0xf6, 0x30, 0x81, 0xbb, 0x2c, 0xe5, 0x81, 0x12, 0x29, 0x41, 0x0e, 0xf2, 0xda, 0xb4, 0x30,
	0xb1, 0x03, 0x9d, 0x24, 0x15, 0xe2, 0x74, 0x9f, 0x47, 0xe3, 0x89, 0x22, 0x77, 0x1c, 0xe4, 0x35,
	0x69, 0xf5, 0x08, 0x3f, 0x82, 0xb6, 0x54, 0x22, 0xe5, 0xfb, 0x81, 0x9c, 0x10, 0xcb, 0x41, 0x5e,
	0x97, 0x96, 0x07, 0xd8, 0x06, 0xd0, 0xc6, 0xfb, 0x55, 0x04, 0x69, 0x6a, 0x77, 0xe5, 0x04, 0xef,
	0x40, 0x4b, 0x27, 0x93, 0x64, 0x4b, 0xfb, 0xd6, 0x16, 0x1e, 0x42, 0x33, 0x8c, 0x42, 0x49, 0x5a,
	0x8e, 0xe5, 0x75, 0x76, 0x1f, 0xf8, 0x1b, 0x30, 0xfc, 0x48, 0xf1, 0x39, 0xd5, 0x32, 0x77, 0x07,
	0xfa, 0x55, 0x20, 0xca, 0x65, 0x22, 0x62, 0xc9, 0xdd, 0x5f, 0x08, 0xb6, 0x8d, 0xe3, 0x5d, 0xca,
	0x43, 0x1e, 0xab, 0x28, 0x98, 0xdd, 0x42, 0xe0, 0xd7, 0xd0, 0x61, 0xa6, 0xbf, 0x1a, 0xdc, 0x55,
	0xb5, 0xfb, 0x18, 0x1e, 0x6e, 0xa0, 0x34, 0x53, 0xf0, 0xa1, 0xb9, 0x8a, 0xc1, 0x3d, 0xb0, 0xa6,
	0x3c, 0xd3, 0xc4, 0x5d, 0xba, 0xfa, 0xc4, 0x7d, 0xd8, 0x3a, 0x0f, 0x66, 0x67, 0x5c, 0x73, 0x76,
	0x69, 0x6e, 0xb8, 0x3f, 0xf2, 0xfd, 0xa0, 0x7c, 0x2e, 0xce, 0xf9, 0x61, 0xc6, 0xfe, 0xb7, 0x71,
	0xe5, 0xdb, 0x62, 0xf0, 0xcc, 0x9c, 0xbe, 0x23, 0xe8, 0x99, 0x39, 0x1e, 0x66, 0xec, 0x20, 0x3e,
	0x15, 0xb7, 0x90, 0xfd, 0x15, 0xdc, 0x0b, 0xa3, 0x70, 0xd5, 0x5c, 0x0d, 0x70, 0x23, 0x75, 0x07,
	0x40, 0xfe, 0x86, 0x2b, 0xc8, 0x77, 0x3f, 0x5b, 0x60, 0x1d, 0xc9, 0x31, 0x3e, 0x86, 0x76, 0x79,
	0x2b, 0x3c, 0xd9, 0x98, 0xb5, 0xfa, 0x9f, 0x0d, 0x9e, 0xff, 0x53, 0x52, 0x94, 0xc0, 0x31, 0xf4,
	0xae, 0xfc, 0x86, 0xde, 0xcd, 0xe1, 0xa5, 0x72, 0xf0, 0xa2, 0xae, 0xd2, 0xd4, 0x3b, 0x86, 0x76,
	0xb9, 0xc0, 0xd7, 0xa2, 0x18, 0xc9, 0xf5, 0x28, 0x57, 0xf6, 0x04, 0x73, 0xb8, 0xff, 0xe7, 0x8e,
	0x3c, 0xbd, 0xb9, 0xbb, 0xb5, 0x6c, 0x30, 0xac, 0x25, 0x2b, 0xca, 0xbc, 0x7d, 0xf3, 0x65, 0x61,
	0xa3, 0xcb, 0x85, 0x8d, 0x7e, 0x2e, 0x6c, 0xf4, 0x69, 0x69, 0x37, 0x2e, 0x97, 0x76, 0xe3, 0xdb,
	0xd2, 0x6e, 0x7c, 0x7c, 0x36, 0x8e, 0xd4, 0xe4, 0xec, 0xc4, 0x67, 0x62, 0x3e, 0x92, 0x6a, 0xa8,
	0x73, 0x8e, 0x8a, 0xfb, 0xff, 0x22, 0x7f, 0x01, 0xb2, 0x84, 0xcb, 0x93, 0x96, 0x7e, 0x05, 0x5e,
	0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x75, 0xef, 0xdc, 0xa9, 0x1d, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	UpdateDID(ctx context.Context, in *MsgUpdateDID, opts ...grpc.CallOption) (*MsgUpdateDIDResponse, error)
	UpdateCredential(ctx context.Context, in *MsgUpdateCredential, opts ...grpc.CallOption) (*MsgUpdateCredentialResponse, error)
	RemoveKyc(ctx context.Context, in *MsgRemoveKyc, opts ...grpc.CallOption) (*MsgRemoveKycResponse, error)
	UpdateKycInfo(ctx context.Context, in *MsgUpdateKycInfo, opts ...grpc.CallOption) (*MsgUpdateKycInfoResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateDID(ctx context.Context, in *MsgUpdateDID, opts ...grpc.CallOption) (*MsgUpdateDIDResponse, error) {
	out := new(MsgUpdateDIDResponse)
	err := c.cc.Invoke(ctx, "/stchain.rollapp.kyc.Msg/UpdateDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCredential(ctx context.Context, in *MsgUpdateCredential, opts ...grpc.CallOption) (*MsgUpdateCredentialResponse, error) {
	out := new(MsgUpdateCredentialResponse)
	err := c.cc.Invoke(ctx, "/stchain.rollapp.kyc.Msg/UpdateCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveKyc(ctx context.Context, in *MsgRemoveKyc, opts ...grpc.CallOption) (*MsgRemoveKycResponse, error) {
	out := new(MsgRemoveKycResponse)
	err := c.cc.Invoke(ctx, "/stchain.rollapp.kyc.Msg/RemoveKyc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateKycInfo(ctx context.Context, in *MsgUpdateKycInfo, opts ...grpc.CallOption) (*MsgUpdateKycInfoResponse, error) {
	out := new(MsgUpdateKycInfoResponse)
	err := c.cc.Invoke(ctx, "/stchain.rollapp.kyc.Msg/UpdateKycInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	UpdateDID(context.Context, *MsgUpdateDID) (*MsgUpdateDIDResponse, error)
	UpdateCredential(context.Context, *MsgUpdateCredential) (*MsgUpdateCredentialResponse, error)
	RemoveKyc(context.Context, *MsgRemoveKyc) (*MsgRemoveKycResponse, error)
	UpdateKycInfo(context.Context, *MsgUpdateKycInfo) (*MsgUpdateKycInfoResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateDID(ctx context.Context, req *MsgUpdateDID) (*MsgUpdateDIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDID not implemented")
}
func (*UnimplementedMsgServer) UpdateCredential(ctx context.Context, req *MsgUpdateCredential) (*MsgUpdateCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCredential not implemented")
}
func (*UnimplementedMsgServer) RemoveKyc(ctx context.Context, req *MsgRemoveKyc) (*MsgRemoveKycResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveKyc not implemented")
}
func (*UnimplementedMsgServer) UpdateKycInfo(ctx context.Context, req *MsgUpdateKycInfo) (*MsgUpdateKycInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKycInfo not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateDID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stchain.rollapp.kyc.Msg/UpdateDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateDID(ctx, req.(*MsgUpdateDID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stchain.rollapp.kyc.Msg/UpdateCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCredential(ctx, req.(*MsgUpdateCredential))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveKyc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveKyc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveKyc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stchain.rollapp.kyc.Msg/RemoveKyc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveKyc(ctx, req.(*MsgRemoveKyc))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateKycInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateKycInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateKycInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stchain.rollapp.kyc.Msg/UpdateKycInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateKycInfo(ctx, req.(*MsgUpdateKycInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stchain.rollapp.kyc.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateDID",
			Handler:    _Msg_UpdateDID_Handler,
		},
		{
			MethodName: "UpdateCredential",
			Handler:    _Msg_UpdateCredential_Handler,
		},
		{
			MethodName: "RemoveKyc",
			Handler:    _Msg_RemoveKyc_Handler,
		},
		{
			MethodName: "UpdateKycInfo",
			Handler:    _Msg_UpdateKycInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollapp/kyc/tx.proto",
}

func (m *MsgUpdateDID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateDID) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateDID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Dids) > 0 {
		for iNdEx := len(m.Dids) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Dids[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Proofs) > 0 {
		i -= len(m.Proofs)
		copy(dAtA[i:], m.Proofs)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proofs)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.StoreProof) > 0 {
		i -= len(m.StoreProof)
		copy(dAtA[i:], m.StoreProof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StoreProof)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StoreHash) > 0 {
		i -= len(m.StoreHash)
		copy(dAtA[i:], m.StoreHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StoreHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ProofHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProofHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateDIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateDIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateDIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCredential) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCredential) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCredential) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Credentials) > 0 {
		for iNdEx := len(m.Credentials) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Credentials[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Proofs) > 0 {
		i -= len(m.Proofs)
		copy(dAtA[i:], m.Proofs)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proofs)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.StoreProof) > 0 {
		i -= len(m.StoreProof)
		copy(dAtA[i:], m.StoreProof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StoreProof)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StoreHash) > 0 {
		i -= len(m.StoreHash)
		copy(dAtA[i:], m.StoreHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StoreHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ProofHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProofHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCredentialResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCredentialResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCredentialResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Item) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Item) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Item) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveKyc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveKyc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveKyc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Credentials) > 0 {
		for iNdEx := len(m.Credentials) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Credentials[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Proofs) > 0 {
		i -= len(m.Proofs)
		copy(dAtA[i:], m.Proofs)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proofs)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.StoreProof) > 0 {
		i -= len(m.StoreProof)
		copy(dAtA[i:], m.StoreProof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StoreProof)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StoreHash) > 0 {
		i -= len(m.StoreHash)
		copy(dAtA[i:], m.StoreHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StoreHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ProofHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProofHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveKycResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveKycResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveKycResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateKycInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateKycInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateKycInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DidInfos) > 0 {
		for iNdEx := len(m.DidInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DidInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Proofs) > 0 {
		i -= len(m.Proofs)
		copy(dAtA[i:], m.Proofs)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proofs)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.StoreProof) > 0 {
		i -= len(m.StoreProof)
		copy(dAtA[i:], m.StoreProof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StoreProof)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StoreHash) > 0 {
		i -= len(m.StoreHash)
		copy(dAtA[i:], m.StoreHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StoreHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ProofHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProofHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateKycInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateKycInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateKycInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateDID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProofHeight != 0 {
		n += 1 + sovTx(uint64(m.ProofHeight))
	}
	l = len(m.StoreHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.StoreProof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proofs)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Dids) > 0 {
		for _, e := range m.Dids {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateDIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateCredential) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProofHeight != 0 {
		n += 1 + sovTx(uint64(m.ProofHeight))
	}
	l = len(m.StoreHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.StoreProof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proofs)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Credentials) > 0 {
		for _, e := range m.Credentials {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateCredentialResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Item) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRemoveKyc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProofHeight != 0 {
		n += 1 + sovTx(uint64(m.ProofHeight))
	}
	l = len(m.StoreHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.StoreProof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proofs)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Credentials) > 0 {
		for _, e := range m.Credentials {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgRemoveKycResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateKycInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProofHeight != 0 {
		n += 1 + sovTx(uint64(m.ProofHeight))
	}
	l = len(m.StoreHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.StoreProof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proofs)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.DidInfos) > 0 {
		for _, e := range m.DidInfos {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateKycInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateDID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateDID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateDID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofHeight", wireType)
			}
			m.ProofHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreHash = append(m.StoreHash[:0], dAtA[iNdEx:postIndex]...)
			if m.StoreHash == nil {
				m.StoreHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreProof = append(m.StoreProof[:0], dAtA[iNdEx:postIndex]...)
			if m.StoreProof == nil {
				m.StoreProof = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proofs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proofs = append(m.Proofs[:0], dAtA[iNdEx:postIndex]...)
			if m.Proofs == nil {
				m.Proofs = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dids", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dids = append(m.Dids, &Item{})
			if err := m.Dids[len(m.Dids)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateDIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateDIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateDIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCredential) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCredential: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCredential: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofHeight", wireType)
			}
			m.ProofHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreHash = append(m.StoreHash[:0], dAtA[iNdEx:postIndex]...)
			if m.StoreHash == nil {
				m.StoreHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreProof = append(m.StoreProof[:0], dAtA[iNdEx:postIndex]...)
			if m.StoreProof == nil {
				m.StoreProof = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proofs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proofs = append(m.Proofs[:0], dAtA[iNdEx:postIndex]...)
			if m.Proofs == nil {
				m.Proofs = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credentials", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Credentials = append(m.Credentials, &Item{})
			if err := m.Credentials[len(m.Credentials)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCredentialResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCredentialResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCredentialResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Item) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: item: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: item: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveKyc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveKyc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveKyc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofHeight", wireType)
			}
			m.ProofHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreHash = append(m.StoreHash[:0], dAtA[iNdEx:postIndex]...)
			if m.StoreHash == nil {
				m.StoreHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreProof = append(m.StoreProof[:0], dAtA[iNdEx:postIndex]...)
			if m.StoreProof == nil {
				m.StoreProof = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proofs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proofs = append(m.Proofs[:0], dAtA[iNdEx:postIndex]...)
			if m.Proofs == nil {
				m.Proofs = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credentials", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Credentials = append(m.Credentials, &Item{})
			if err := m.Credentials[len(m.Credentials)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveKycResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveKycResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveKycResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateKycInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateKycInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateKycInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofHeight", wireType)
			}
			m.ProofHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreHash = append(m.StoreHash[:0], dAtA[iNdEx:postIndex]...)
			if m.StoreHash == nil {
				m.StoreHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreProof = append(m.StoreProof[:0], dAtA[iNdEx:postIndex]...)
			if m.StoreProof == nil {
				m.StoreProof = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proofs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proofs = append(m.Proofs[:0], dAtA[iNdEx:postIndex]...)
			if m.Proofs == nil {
				m.Proofs = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidInfos = append(m.DidInfos, &Item{})
			if err := m.DidInfos[len(m.DidInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateKycInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateKycInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateKycInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
