// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollapp/region/fee_collector.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FeeCollector struct {
	Index string       `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Fees  []types.Coin `protobuf:"bytes,2,rep,name=fees,proto3" json:"fees"`
}

func (m *FeeCollector) Reset()         { *m = FeeCollector{} }
func (m *FeeCollector) String() string { return proto.CompactTextString(m) }
func (*FeeCollector) ProtoMessage()    {}
func (*FeeCollector) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fbbf38d7f06e8f, []int{0}
}
func (m *FeeCollector) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeCollector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeCollector.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeCollector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeCollector.Merge(m, src)
}
func (m *FeeCollector) XXX_Size() int {
	return m.Size()
}
func (m *FeeCollector) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeCollector.DiscardUnknown(m)
}

var xxx_messageInfo_FeeCollector proto.InternalMessageInfo

func (m *FeeCollector) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *FeeCollector) GetFees() []types.Coin {
	if m != nil {
		return m.Fees
	}
	return nil
}

func init() {
	proto.RegisterType((*FeeCollector)(nil), "stchain.rollapp.region.FeeCollector")
}

func init() {
	proto.RegisterFile("rollapp/region/fee_collector.proto", fileDescriptor_04fbbf38d7f06e8f)
}

var fileDescriptor_04fbbf38d7f06e8f = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0x40, 0xb7, 0x8a, 0x26, 0xae, 0x9e, 0x36, 0xc4, 0x20, 0x87, 0x4a, 0x38, 0x11, 0x13, 0x67,
	0x82, 0xfc, 0x01, 0x18, 0x3f, 0x80, 0x9b, 0x5e, 0xcc, 0x6e, 0x1d, 0x96, 0x26, 0x4b, 0x67, 0xd3,
	0x56, 0x83, 0x7f, 0xe1, 0x67, 0x71, 0xe4, 0xe8, 0xc9, 0x98, 0xdd, 0x1f, 0x21, 0xb4, 0xec, 0xad,
	0xcd, 0xbc, 0xbc, 0x99, 0x97, 0x8e, 0x2d, 0x57, 0x55, 0x5e, 0xd7, 0x68, 0xa9, 0xd4, 0x6c, 0x70,
	0x45, 0xf4, 0xae, 0xb8, 0xaa, 0x48, 0x79, 0xb6, 0x50, 0x5b, 0xf6, 0x9c, 0xdd, 0x3a, 0xaf, 0xd6,
	0xb9, 0x36, 0x70, 0x62, 0x21, 0xb2, 0xc3, 0x7e, 0xc9, 0x25, 0x07, 0x04, 0x8f, 0xaf, 0x48, 0x0f,
	0xa5, 0x62, 0xb7, 0x61, 0x87, 0x45, 0xee, 0x08, 0xbf, 0xa6, 0x05, 0xf9, 0x7c, 0x8a, 0x8a, 0xb5,
	0x89, 0xf3, 0xf1, 0x6b, 0x7a, 0xf3, 0x42, 0xb4, 0xe8, 0x76, 0x64, 0xfd, 0xf4, 0x42, 0x9b, 0x0f,
	0xda, 0x0e, 0xc4, 0x48, 0x4c, 0xae, 0x96, 0xf1, 0x93, 0xcd, 0xd2, 0xde, 0x8a, 0xc8, 0x0d, 0xce,
	0x46, 0xe7, 0x93, 0xeb, 0xa7, 0x3b, 0x88, 0x52, 0x38, 0x4a, 0xe1, 0x24, 0x85, 0x05, 0x6b, 0x33,
	0xef, 0xed, 0xfe, 0xee, 0x93, 0x65, 0x80, 0xe7, 0xcf, 0xbb, 0x46, 0x8a, 0x7d, 0x23, 0xc5, 0x7f,
	0x23, 0xc5, 0x4f, 0x2b, 0x93, 0x7d, 0x2b, 0x93, 0xdf, 0x56, 0x26, 0x6f, 0x0f, 0xa5, 0xf6, 0xeb,
	0xcf, 0x02, 0x14, 0x6f, 0xd0, 0xf9, 0xc7, 0x90, 0x83, 0x5d, 0xfa, 0xb6, 0x8b, 0xf7, 0xdf, 0x35,
	0xb9, 0xe2, 0x32, 0xdc, 0x39, 0x3b, 0x04, 0x00, 0x00, 0xff, 0xff, 0x95, 0xa5, 0xa2, 0x1d, 0x1b,
	0x01, 0x00, 0x00,
}

func (m *FeeCollector) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeCollector) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeCollector) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Fees) > 0 {
		for iNdEx := len(m.Fees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Fees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeeCollector(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintFeeCollector(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFeeCollector(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeeCollector(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeCollector) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovFeeCollector(uint64(l))
	}
	if len(m.Fees) > 0 {
		for _, e := range m.Fees {
			l = e.Size()
			n += 1 + l + sovFeeCollector(uint64(l))
		}
	}
	return n
}

func sovFeeCollector(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeeCollector(x uint64) (n int) {
	return sovFeeCollector(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeCollector) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeeCollector
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeCollector: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeCollector: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeCollector
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeCollector
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeCollector
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeCollector
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fees = append(m.Fees, types.Coin{})
			if err := m.Fees[len(m.Fees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeeCollector(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeeCollector
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeeCollector(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeeCollector
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeCollector
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeCollector
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeeCollector
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeeCollector
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeeCollector
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeeCollector        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeeCollector          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeeCollector = fmt.Errorf("proto: unexpected end of group")
)
