// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollapp/region/region.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Region struct {
	RegionId           string `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	OperatorAddress    string `protobuf:"bytes,2,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	RegionTreasureAddr string `protobuf:"bytes,3,opt,name=region_treasure_addr,json=regionTreasureAddr,proto3" json:"region_treasure_addr,omitempty"`
}

func (m *Region) Reset()         { *m = Region{} }
func (m *Region) String() string { return proto.CompactTextString(m) }
func (*Region) ProtoMessage()    {}
func (*Region) Descriptor() ([]byte, []int) {
	return fileDescriptor_5888d0ea5a9a5f42, []int{0}
}
func (m *Region) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Region) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Region.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Region) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Region.Merge(m, src)
}
func (m *Region) XXX_Size() int {
	return m.Size()
}
func (m *Region) XXX_DiscardUnknown() {
	xxx_messageInfo_Region.DiscardUnknown(m)
}

var xxx_messageInfo_Region proto.InternalMessageInfo

func (m *Region) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *Region) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *Region) GetRegionTreasureAddr() string {
	if m != nil {
		return m.RegionTreasureAddr
	}
	return ""
}

type MeHubRegionType struct {
	RegionId            string `protobuf:"bytes,1,opt,name=regionId,proto3" json:"regionId,omitempty"`
	Name                string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Creator             string `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	OperatorAddress     string `protobuf:"bytes,4,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	NftClassId          string `protobuf:"bytes,5,opt,name=nft_class_id,json=nftClassId,proto3" json:"nft_class_id,omitempty"`
	RegionTreasureAddr  string `protobuf:"bytes,6,opt,name=region_treasure_addr,json=regionTreasureAddr,proto3" json:"region_treasure_addr,omitempty"`
	DepositInterestAddr string `protobuf:"bytes,8,opt,name=deposit_interest_addr,json=depositInterestAddr,proto3" json:"deposit_interest_addr,omitempty"`
	// tokens define the region tokens share
	RegionShare        github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,9,opt,name=region_share,json=regionShare,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"region_share"`
	DelegateInterest   github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,10,opt,name=delegate_interest,json=delegateInterest,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"delegate_interest"`
	DelegateAmount     github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,11,opt,name=delegate_amount,json=delegateAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"delegate_amount"`
	FixedDepositAmount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,12,opt,name=fixed_deposit_amount,json=fixedDepositAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"fixed_deposit_amount"`
}

func (m *MeHubRegionType) Reset()         { *m = MeHubRegionType{} }
func (m *MeHubRegionType) String() string { return proto.CompactTextString(m) }
func (*MeHubRegionType) ProtoMessage()    {}
func (*MeHubRegionType) Descriptor() ([]byte, []int) {
	return fileDescriptor_5888d0ea5a9a5f42, []int{1}
}
func (m *MeHubRegionType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MeHubRegionType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MeHubRegionType.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MeHubRegionType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeHubRegionType.Merge(m, src)
}
func (m *MeHubRegionType) XXX_Size() int {
	return m.Size()
}
func (m *MeHubRegionType) XXX_DiscardUnknown() {
	xxx_messageInfo_MeHubRegionType.DiscardUnknown(m)
}

var xxx_messageInfo_MeHubRegionType proto.InternalMessageInfo

func (m *MeHubRegionType) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *MeHubRegionType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MeHubRegionType) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MeHubRegionType) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *MeHubRegionType) GetNftClassId() string {
	if m != nil {
		return m.NftClassId
	}
	return ""
}

func (m *MeHubRegionType) GetRegionTreasureAddr() string {
	if m != nil {
		return m.RegionTreasureAddr
	}
	return ""
}

func (m *MeHubRegionType) GetDepositInterestAddr() string {
	if m != nil {
		return m.DepositInterestAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*Region)(nil), "stchain.rollapp.region.Region")
	proto.RegisterType((*MeHubRegionType)(nil), "stchain.rollapp.region.MeHubRegionType")
}

func init() { proto.RegisterFile("rollapp/region/region.proto", fileDescriptor_5888d0ea5a9a5f42) }

var fileDescriptor_5888d0ea5a9a5f42 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x1b, 0xd8, 0xca, 0xfa, 0x56, 0xd1, 0x61, 0x0a, 0x0a, 0x9d, 0x94, 0x4d, 0x3b, 0x20,
	0x84, 0xd4, 0xf4, 0xc0, 0x95, 0xcb, 0xb6, 0x1e, 0x08, 0x82, 0x4b, 0xb6, 0x13, 0x97, 0xc8, 0x8d,
	0x5f, 0x53, 0x8b, 0xd6, 0x8e, 0x6c, 0x57, 0xda, 0xbe, 0x05, 0x1f, 0x66, 0xe2, 0x33, 0xec, 0x38,
	0xed, 0x84, 0x38, 0x4c, 0xa8, 0xfd, 0x20, 0xa0, 0xd8, 0x4e, 0x35, 0x09, 0xd0, 0x54, 0xa9, 0xa7,
	0xd8, 0xcf, 0xfe, 0xff, 0xfe, 0xff, 0xe7, 0x56, 0x0f, 0xf6, 0x95, 0x9c, 0x4e, 0x69, 0x59, 0x0e,
	0x14, 0x16, 0x5c, 0x0a, 0xff, 0x89, 0x4b, 0x25, 0x8d, 0x24, 0x2f, 0xb5, 0xc9, 0x27, 0x94, 0x8b,
	0xd8, 0x5f, 0x8a, 0xdd, 0x69, 0xef, 0x55, 0x2e, 0xf5, 0x4c, 0xea, 0xcc, 0xde, 0x1a, 0xb8, 0x8d,
	0x93, 0xf4, 0xba, 0x85, 0x2c, 0xa4, 0xab, 0x57, 0x2b, 0x57, 0x3d, 0xfa, 0x1e, 0x40, 0x33, 0xb5,
	0x5a, 0xb2, 0x0f, 0x2d, 0x47, 0xc9, 0x38, 0x0b, 0x83, 0xc3, 0xe0, 0x4d, 0x2b, 0xdd, 0x71, 0x85,
	0x84, 0x91, 0x53, 0xd8, 0x93, 0x25, 0x2a, 0x6a, 0xa4, 0xca, 0x28, 0x63, 0x0a, 0xb5, 0x0e, 0x1f,
	0x55, 0x77, 0x4e, 0xc2, 0xdb, 0xab, 0x7e, 0xd7, 0x3b, 0x1d, 0xbb, 0x93, 0x33, 0xa3, 0xb8, 0x28,
	0xd2, 0x4e, 0xad, 0xf0, 0x65, 0xf2, 0x11, 0xba, 0xde, 0xc1, 0x28, 0xa4, 0x7a, 0xae, 0xd0, 0xb2,
	0xc2, 0xc7, 0x0f, 0x80, 0x88, 0x53, 0x9d, 0x7b, 0x51, 0x75, 0x78, 0xf4, 0x7b, 0x1b, 0x3a, 0x9f,
	0xf1, 0xc3, 0x7c, 0xe4, 0xd2, 0x9f, 0x5f, 0x96, 0x48, 0x7a, 0xb0, 0x0a, 0xfc, 0x57, 0x03, 0x04,
	0xb6, 0x04, 0x9d, 0xa1, 0x0b, 0x9d, 0xda, 0x35, 0x09, 0xe1, 0x49, 0xae, 0xb0, 0x4a, 0xe8, 0x22,
	0xa4, 0xf5, 0xf6, 0x9f, 0xed, 0x6e, 0xad, 0xdb, 0xee, 0x21, 0xb4, 0xc5, 0xd8, 0x64, 0xf9, 0x94,
	0x6a, 0x5d, 0xbd, 0xe9, 0xb6, 0xf5, 0x00, 0x31, 0x36, 0xa7, 0x55, 0x29, 0x61, 0xff, 0x7d, 0x90,
	0xe6, 0xfa, 0x0f, 0x42, 0x3e, 0xc1, 0x0b, 0x86, 0xa5, 0xd4, 0xdc, 0x64, 0x5c, 0x18, 0x54, 0xa8,
	0x8d, 0x83, 0xed, 0x3c, 0x00, 0x7b, 0xee, 0x65, 0x89, 0x57, 0x59, 0x5a, 0x06, 0x6d, 0x9f, 0x4c,
	0x4f, 0xa8, 0xc2, 0xb0, 0x65, 0x21, 0xef, 0xaf, 0xef, 0x0e, 0x1a, 0x3f, 0xef, 0x0e, 0x5e, 0x17,
	0xdc, 0x4c, 0xe6, 0xa3, 0x38, 0x97, 0x33, 0xff, 0x27, 0xf3, 0x9f, 0xbe, 0x66, 0x5f, 0x07, 0xe6,
	0xb2, 0x44, 0x1d, 0x27, 0xc2, 0xdc, 0x5e, 0xf5, 0xc1, 0x5b, 0x26, 0xc2, 0xa4, 0xbb, 0x8e, 0x78,
	0x56, 0x01, 0x09, 0x87, 0x67, 0x0c, 0xa7, 0x58, 0x50, 0x83, 0xab, 0xbc, 0x21, 0xac, 0xed, 0x32,
	0xc4, 0xfc, 0x9e, 0xcb, 0x10, 0xf3, 0x74, 0xaf, 0xc6, 0xd6, 0xfd, 0x10, 0x84, 0xce, 0xca, 0x8a,
	0xce, 0xe4, 0x5c, 0x98, 0x70, 0x77, 0x03, 0xed, 0x3c, 0xad, 0xa1, 0xc7, 0x96, 0x49, 0x04, 0x74,
	0xc7, 0xfc, 0x02, 0x59, 0x56, 0xff, 0x0c, 0xde, 0xab, 0xbd, 0x01, 0x2f, 0x62, 0xc9, 0x43, 0x07,
	0x76, 0x7e, 0x27, 0xc3, 0xeb, 0x45, 0x14, 0xdc, 0x2c, 0xa2, 0xe0, 0xd7, 0x22, 0x0a, 0xbe, 0x2d,
	0xa3, 0xc6, 0xcd, 0x32, 0x6a, 0xfc, 0x58, 0x46, 0x8d, 0x2f, 0x6f, 0xef, 0x79, 0x68, 0xd3, 0xb7,
	0x93, 0x62, 0x50, 0x8f, 0x93, 0x8b, 0x7a, 0xa0, 0x58, 0xaf, 0x51, 0xd3, 0xce, 0x81, 0x77, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x81, 0x0e, 0x5d, 0xee, 0x6f, 0x04, 0x00, 0x00,
}

func (m *Region) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Region) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Region) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RegionTreasureAddr) > 0 {
		i -= len(m.RegionTreasureAddr)
		copy(dAtA[i:], m.RegionTreasureAddr)
		i = encodeVarintRegion(dAtA, i, uint64(len(m.RegionTreasureAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintRegion(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintRegion(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MeHubRegionType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MeHubRegionType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MeHubRegionType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.FixedDepositAmount.Size()
		i -= size
		if _, err := m.FixedDepositAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRegion(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	{
		size := m.DelegateAmount.Size()
		i -= size
		if _, err := m.DelegateAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRegion(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size := m.DelegateInterest.Size()
		i -= size
		if _, err := m.DelegateInterest.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRegion(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size := m.RegionShare.Size()
		i -= size
		if _, err := m.RegionShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRegion(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if len(m.DepositInterestAddr) > 0 {
		i -= len(m.DepositInterestAddr)
		copy(dAtA[i:], m.DepositInterestAddr)
		i = encodeVarintRegion(dAtA, i, uint64(len(m.DepositInterestAddr)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.RegionTreasureAddr) > 0 {
		i -= len(m.RegionTreasureAddr)
		copy(dAtA[i:], m.RegionTreasureAddr)
		i = encodeVarintRegion(dAtA, i, uint64(len(m.RegionTreasureAddr)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.NftClassId) > 0 {
		i -= len(m.NftClassId)
		copy(dAtA[i:], m.NftClassId)
		i = encodeVarintRegion(dAtA, i, uint64(len(m.NftClassId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintRegion(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintRegion(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintRegion(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintRegion(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRegion(dAtA []byte, offset int, v uint64) int {
	offset -= sovRegion(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Region) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	l = len(m.RegionTreasureAddr)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	return n
}

func (m *MeHubRegionType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	l = len(m.NftClassId)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	l = len(m.RegionTreasureAddr)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	l = len(m.DepositInterestAddr)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	l = m.RegionShare.Size()
	n += 1 + l + sovRegion(uint64(l))
	l = m.DelegateInterest.Size()
	n += 1 + l + sovRegion(uint64(l))
	l = m.DelegateAmount.Size()
	n += 1 + l + sovRegion(uint64(l))
	l = m.FixedDepositAmount.Size()
	n += 1 + l + sovRegion(uint64(l))
	return n
}

func sovRegion(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRegion(x uint64) (n int) {
	return sovRegion(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Region) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Region: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Region: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionTreasureAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionTreasureAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MeHubRegionType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MeHubRegionType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MeHubRegionType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftClassId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftClassId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionTreasureAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionTreasureAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositInterestAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositInterestAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RegionShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegateInterest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegateInterest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegateAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegateAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FixedDepositAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FixedDepositAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRegion(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRegion
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRegion
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRegion
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRegion
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRegion        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRegion          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRegion = fmt.Errorf("proto: unexpected end of group")
)
